export type LocalizedText = {
  tr: string;
  en: string;
  zh?: string;
  de?: string; // Almanca
  nl?: string; // Hollandaca
  es?: string; // İspanyolca
  fr?: string; // Fransızca
  it?: string; // İtalyanca
};

type MirrorHour = {
  time: string;
  title: LocalizedText;
  meaning: LocalizedText;
  category: string;
  // Rich content fields for SEO
  numerology?: LocalizedText;
  astrology?: LocalizedText;
  loveAndRelationships?: LocalizedText;
  careerAndMoney?: LocalizedText;
  spiritualGuidance?: LocalizedText;
  actionSteps?: LocalizedText;
};

const mirrorHoursData: MirrorHour[] = [
  {
    time: "00:00",
    title: {
      tr: "Yeni bir döngü başlıyor",
      en: "A new cycle begins",
      zh: "新的循环开始",
      de: "Ein neuer Zyklus beginnt",
      nl: "Een nieuwe cyclus begint",
      es: "Comienza un nuevo ciclo",
      fr: "Un nouveau cycle commence",
      it: "Inizia un nuovo ciclo",
    },
    meaning: {
      tr: "Evren sana yepyeni bir başlangıç sunuyor. Geçmişi arkanda bırakmak ve cesur adımlar atmak için doğru zamandasın.",
      en: "The universe offers you a brand new beginning. It's the right time to leave the past behind and take brave steps forward.",
      zh: "宇宙为你提供了一个全新的开始。现在是放下过去、勇敢向前迈进的正确时机。",
      de: "Das Universum bietet dir einen brandneuen Anfang. Es ist die richtige Zeit, die Vergangenheit hinter sich zu lassen und mutige Schritte nach vorne zu machen.",
      nl: "Het universum biedt je een gloednieuw begin. Het is het juiste moment om het verleden achter je te laten en dappere stappen vooruit te zetten.",
      es: "El universo te ofrece un nuevo comienzo. Es el momento adecuado para dejar atrás el pasado y dar pasos valientes hacia adelante.",
      fr: "L'univers vous offre un tout nouveau départ. C'est le bon moment pour laisser le passé derrière soi et faire des pas courageux vers l'avant.",
      it: "L'universo ti offre un nuovo inizio. È il momento giusto per lasciarsi il passato alle spalle e fare passi coraggiosi in avanti.",
    },
    category: "Tam Ayna",
    numerology: {
      tr: "00:00, gece yarısı ve yeni bir günün başlangıcıdır. Numerolojide 0, sonsuz potansiyeli, boşluğu ve her şeyin kaynağını temsil eder...",
      en: "00:00 is midnight and the beginning of a new day. In numerology, 0 represents infinite potential, the void, and the source of everything...",
      zh: "00:00是午夜，也是新一天的开始。在数字命理学中，0代表无限的潜力、虚空和万物的源头...",
      de: "00:00 ist Mitternacht und der Beginn eines neuen Tages. In der Numerologie steht die 0 für unendliches Potenzial, die Leere und die Quelle von allem. Vier Nullen zusammen sind die mächtigste Form dieser Energie.",
      nl: "00:00 is middernacht en het begin van een nieuwe dag. In de numerologie staat 0 voor oneindig potentieel, de leegte en de bron van alles. Vier nullen samen is de krachtigste vorm van deze energie.",
      es: "00:00 es medianoche y el comienzo de un nuevo día. En numerología, el 0 representa el potencial infinito, el vacío y la fuente de todo. Cuatro ceros juntos son la forma más poderosa de esta energía.",
      fr: "00:00 est minuit et le début d'un nouveau jour. En numérologie, le 0 représente le potentiel infini, le vide et la source de tout. Quatre zéros ensemble sont la forme la plus puissante de cette énergie.",
      it: "00:00 è mezzanotte e l'inizio di un nuovo giorno. In numerologia, lo 0 rappresenta il potenziale infinito, il vuoto e la fonte di tutto. Quattro zeri insieme sono la forma più potente di questa energia.",
    },
    astrology: {
      tr: "Astrolojik olarak 00:00, Güneş'in gece yarısı konumudur...",
      en: "Astrologically, 00:00 is the Sun's midnight position...",
      zh: "从占星学角度来看，00:00是太阳的午夜位置...",
      de: "Astrologisch gesehen ist 00:00 die Mitternachtsposition der Sonne – am tiefsten, am dunkelsten, aber kurz vor der Wiedergeburt. Sie schwingt mit der Transformationsenergie von Pluto mit.",
      nl: "Astrologisch gezien is 00:00 de middernachtpositie van de zon - op zijn diepst, donkerst, maar net voor de wedergeboorte. Het resoneert met de transformatie-energie van Pluto.",
      es: "Astrológicamente, 00:00 es la posición de medianoche del Sol: en su punto más profundo y oscuro, pero justo antes del renacimiento. Resuena con la energía transformadora de Plutón.",
      fr: "Astrologiquement, 00:00 est la position de minuit du Soleil - au plus profond, au plus sombre, mais juste avant la renaissance. Il résonne avec l'énergie de transformation de Pluton.",
      it: "Astrologicamente, 00:00 è la posizione di mezzanotte del Sole - nel punto più profondo e oscuro, ma appena prima della rinascita. Risuona con l'energia di trasformazione di Plutone.",
    },
    loveAndRelationships: {
      tr: "Aşk hayatınız için 00:00, yepyeni bir başlangıç yapmak isteyenler için mükemmel bir saattir...",
      en: "For your love life, 00:00 is perfect for those wanting to make a brand new start...",
      zh: "对于你的爱情生活，00:00对于那些想要全新开始的人来说是完美的时刻...",
      de: "Für dein Liebesleben ist 00:00 perfekt für diejenigen, die einen brandneuen Start machen wollen. Es ist Zeit, sich von alten Beziehungen und Schmerzen zu reinigen.",
      nl: "Voor je liefdesleven is 00:00 perfect voor degenen die een gloednieuwe start willen maken. Het is tijd om je te reinigen van oude relaties en pijnen.",
      es: "Para tu vida amorosa, 00:00 es perfecto para aquellos que quieren hacer un nuevo comienzo. Es hora de limpiarse de viejas relaciones y dolores.",
      fr: "Pour votre vie amoureuse, 00:00 est parfait pour ceux qui veulent prendre un tout nouveau départ. Il est temps de se purifier des anciennes relations et des douleurs.",
      it: "Per la tua vita amorosa, 00:00 è perfetto per chi vuole fare un nuovo inizio. È tempo di purificarsi da vecchie relazioni e dolori.",
    },
    careerAndMoney: {
      tr: "Kariyer açısından 00:00, yeni bir işe başlamak...",
      en: "Career-wise, 00:00 is powerful energy for starting a new job...",
      zh: "从职业角度来看，00:00是开始新工作...",
      de: "Beruflich ist 00:00 eine kraftvolle Energie, um einen neuen Job zu beginnen oder ein Startup zu gründen. Hab keine Angst, finanziell bei Null anzufangen.",
      nl: "Op carrièregebied is 00:00 krachtige energie voor het starten van een nieuwe baan of het oprichten van een startup. Wees niet bang om financieel vanaf nul te beginnen.",
      es: "En cuanto a la carrera, 00:00 es una energía poderosa para comenzar un nuevo trabajo o fundar una startup. No tengas miedo de empezar de cero financieramente.",
      fr: "Sur le plan professionnel, 00:00 est une énergie puissante pour commencer un nouvel emploi ou fonder une startup. N'ayez pas peur de repartir de zéro financièrement.",
      it: "Dal punto di vista lavorativo, 00:00 è un'energia potente per iniziare un nuovo lavoro o fondare una startup. Non aver paura di ripartire da zero finanziariamente.",
    },
    spiritualGuidance: {
      tr: "Ruhsal olarak 00:00, en derin iç yolculuk saatidir...",
      en: "Spiritually, 00:00 is the hour of the deepest inner journey...",
      zh: "在灵性层面上，00:00是最深层内在旅程的时刻...",
      de: "Spirituell ist 00:00 die Stunde der tiefsten inneren Reise. Es ist eine ideale Zeit für Meditation und Energierreinigung.",
      nl: "Spiritueel is 00:00 het uur van de diepste innerlijke reis. Het is een ideale tijd voor meditatie en energiereiniging.",
      es: "Espiritualmente, 00:00 es la hora del viaje interior más profundo. Es un momento ideal para la meditación y la limpieza energética.",
      fr: "Spirituellement, 00:00 est l'heure du voyage intérieur le plus profond. C'est un moment idéal pour la méditation et le nettoyage énergétique.",
      it: "Spiritualmente, 00:00 è l'ora del viaggio interiore più profondo. È un momento ideale per la meditazione e la pulizia energetica.",
    },
    actionSteps: {
      tr: "• Bir kağıda bırakmak istediğiniz her şeyi yazın...",
      en: "• Write everything you want to let go of on paper...",
      zh: "• 在纸上写下你想放下的一切...",
      de: "• Schreibe alles, was du loslassen möchtest, auf ein Papier\n• Schaue in den Spiegel und sage 'Das alte Ich ist weg, das neue Ich ist hier'",
      nl: "• Schrijf alles wat je wilt loslaten op papier\n• Kijk in de spiegel en zeg 'De oude ik is weg, de nieuwe ik is hier'",
      es: "• Escribe todo lo que quieras soltar en un papel\n• Mírate al espejo y di 'El viejo yo se ha ido, el nuevo yo está aquí'",
      fr: "• Écrivez tout ce que vous voulez laisser aller sur un papier\n• Regardez-vous dans le miroir et dites 'L'ancien moi est parti, le nouveau moi est ici'",
      it: "• Scrivi tutto ciò che vuoi lasciare andare su un foglio\n• Guardati allo specchio e dì 'Il vecchio me è andato, il nuovo me è qui'",
    },
  },
  {
    time: "01:01",
    title: {
      tr: "Göz önündesin",
      en: "You're in the spotlight",
      zh: "你在聚光灯下",
      de: "Du stehst im Rampenlicht",
      nl: "Je staat in de schijnwerpers",
      es: "Estás en el centro de atención",
      fr: "Vous êtes sous les projecteurs",
      it: "Sei sotto i riflettori",
    },
    meaning: {
      tr: "Biri seni dikkatle izliyor ve sana dair güçlü duygular besliyor. Bu ilgi seni rahatsız etmiyorsa kendini açmayı düşünebilirsin.",
      en: "Someone is watching you carefully and harboring strong feelings for you. If this attention doesn't bother you, you might consider opening up.",
      zh: "有人在仔细观察你，对你怀有强烈的感情。如果这种关注不会让你感到困扰，你可以考虑敞开心扉。",
      de: "Jemand beobachtet dich genau und hegt starke Gefühle für dich. Wenn dich diese Aufmerksamkeit nicht stört, könntest du in Betracht ziehen, dich zu öffnen.",
      nl: "Iemand houdt je nauwlettend in de gaten en koestert sterke gevoelens voor je. Als deze aandacht je niet stoort, kun je overwegen je open te stellen.",
      es: "Alguien te observa atentamente y alberga fuertes sentimientos por ti. Si esta atención no te molesta, podrías considerar abrirte.",
      fr: "Quelqu'un vous observe attentivement et nourrit des sentiments forts pour vous. Si cette attention ne vous dérange pas, vous pourriez envisager de vous ouvrir.",
      it: "Qualcuno ti osserva attentamente e nutre forti sentimenti per te. Se questa attenzione non ti disturba, potresti considerare di aprirti.",
    },
    category: "Tam Ayna",
    numerology: {
      tr: "01:01 saati, 1 rakamının iki kez tekrarlandığı güçlü bir kombinasyondur...",
      en: "The time 01:01 is a powerful combination where the number 1 is repeated twice...",
      zh: "01:01是数字1重复两次的强大组合...",
      de: "Die Uhrzeit 01:01 ist eine kraftvolle Kombination, bei der die Zahl 1 zweimal wiederholt wird. In der Numerologie steht die 1 für Neuanfänge und Führung.",
      nl: "De tijd 01:01 is een krachtige combinatie waarbij het getal 1 twee keer wordt herhaald. In de numerologie staat het getal 1 voor een nieuw begin en leiderschap.",
      es: "La hora 01:01 es una combinación poderosa donde el número 1 se repite dos veces. En numerología, el número 1 representa nuevos comienzos y liderazgo.",
      fr: "L'heure 01:01 est une combinaison puissante où le chiffre 1 est répété deux fois. En numérologie, le chiffre 1 représente les nouveaux départs et le leadership.",
      it: "L'ora 01:01 è una combinazione potente in cui il numero 1 si ripete due volte. In numerologia, il numero 1 rappresenta nuovi inizi e leadership.",
    },
    // Diğer alanlar için de benzer şekilde çeviriler eklenebilir...
    astrology: {
      tr: "Astrolojik açıdan 01:01, Güneş'in enerjisini taşır...",
      en: "Astrologically, 01:01 carries the energy of the Sun...",
      zh: "从占星学角度来看，01:01承载着太阳的能量...",
      de: "Astrologisch gesehen trägt 01:01 die Energie der Sonne. Die Sonne ist der Planet der persönlichen Identität und des Selbstvertrauens.",
      nl: "Astrologisch gezien draagt 01:01 de energie van de Zon. De Zon is de planeet van persoonlijke identiteit en zelfvertrouwen.",
      es: "Astrológicamente, 01:01 lleva la energía del Sol. El Sol es el planeta de la identidad personal y la autoconfianza.",
      fr: "Astrologiquement, 01:01 porte l'énergie du Soleil. Le Soleil est la planète de l'identité personnelle et de la confiance en soi.",
      it: "Astrologicamente, 01:01 porta l'energia del Sole. Il Sole è il pianeta dell'identità personale e della fiducia in se stessi.",
    },
  },
  {
    time: "02:02",
    title: {
      tr: "Sessiz sevgi",
      en: "Silent love",
      zh: "无声的爱",
      de: "Stille Liebe",
      nl: "Stille liefde",
      es: "Amor silencioso",
      fr: "Amour silencieux",
      it: "Amore silenzioso",
    },
    meaning: {
      tr: "Birinin sana karşı hisleri var ama bunları açıkça dile getiremiyor. Kalbindeki sessizliği hissetmeye çalış.",
      en: "Someone has feelings for you but can't express them openly. Try to feel the silence in their heart.",
      zh: "有人对你有感情，但无法公开表达。试着感受他们心中的沉默。",
      de: "Jemand hat Gefühle für dich, kann sie aber nicht offen ausdrücken. Versuche, die Stille in seinem Herzen zu fühlen.",
      nl: "Iemand heeft gevoelens voor je, maar kan ze niet openlijk uiten. Probeer de stilte in hun hart te voelen.",
      es: "Alguien tiene sentimientos por ti pero no puede expresarlos abiertamente. Intenta sentir el silencio en su corazón.",
      fr: "Quelqu'un a des sentiments pour vous mais ne peut pas les exprimer ouvertement. Essayez de ressentir le silence dans son cœur.",
      it: "Qualcuno prova dei sentimenti per te ma non riesce a esprimerli apertamente. Cerca di sentire il silenzio nel suo cuore.",
    },
    category: "Tam Ayna",
    numerology: {
      tr: "02:02, 2 rakamının dört kez tekrarlanmasıyla oluşan...",
      en: "02:02 possesses an extremely sensitive and feminine energy...",
      zh: "02:02拥有极其敏感和阴柔的能量...",
    },
  },
  {
    time: "03:03",
    title: {
      tr: "Zihninde sen varsın",
      en: "You're on their mind",
      zh: "你在他们的脑海中",
      de: "Du bist in ihren Gedanken",
      nl: "Je bent in hun gedachten",
      es: "Estás en su mente",
      fr: "Vous êtes dans leurs pensées",
      it: "Sei nei loro pensieri",
    },
    meaning: {
      tr: "Seni sürekli düşünen biri var, özellikle geceleri. Bu bağ düşündüğünden daha derin olabilir.",
      en: "Someone is constantly thinking about you, especially at night. This connection might be deeper than you think.",
      zh: "有人一直在想你，尤其是在晚上。这种联系可能比你想象的更深。",
      de: "Jemand denkt ständig an dich, besonders nachts. Diese Verbindung könnte tiefer sein, als du denkst.",
      nl: "Iemand denkt constant aan je, vooral 's nachts. Deze band is misschien dieper dan je denkt.",
      es: "Alguien piensa constantemente en ti, especialmente por la noche. Esta conexión podría ser más profunda de lo que piensas.",
      fr: "Quelqu'un pense constamment à vous, surtout la nuit. Cette connexion pourrait être plus profonde que vous ne le pensez.",
      it: "Qualcuno ti pensa costantemente, specialmente di notte. Questa connessione potrebbe essere più profonda di quanto pensi.",
    },
    category: "Tam Ayna",
  },
  {
    time: "04:04",
    title: {
      tr: "Koruyucu enerjiler aktif",
      en: "Protective energies active",
      zh: "保护能量活跃",
      de: "Schutzenergien aktiv",
      nl: "Beschermende energieën actief",
      es: "Energías protectoras activas",
      fr: "Énergies protectrices actives",
      it: "Energie protettive attive",
    },
    meaning: {
      tr: "Hayatında görünmeyen ama güçlü bir koruyucu enerji seni izliyor. Ruhsal destek sana çok yakın.",
      en: "An invisible but strong protective energy is watching over you. Spiritual support is very close to you.",
      zh: "一股看不见但强大的保护能量正在注视着你。精神支持离你很近。",
      de: "Eine unsichtbare, aber starke Schutzenergie wacht über dich. Spirituelle Unterstützung ist dir sehr nahe.",
      nl: "Een onzichtbare maar sterke beschermende energie waakt over je. Spirituele steun is heel dicht bij je.",
      es: "Una energía protectora invisible pero fuerte te está vigilando. El apoyo espiritual está muy cerca de ti.",
      fr: "Une énergie protectrice invisible mais forte veille sur vous. Le soutien spirituel est très proche de vous.",
      it: "Un'energia protettiva invisibile ma forte veglia su di te. Il supporto spirituale è molto vicino a te.",
    },
    category: "Tam Ayna",
  },
  {
    time: "05:05",
    title: {
      tr: "Geçmiş kapıyı çalabilir",
      en: "The past may knock",
      zh: "过去可能会敲门",
      de: "Die Vergangenheit könnte anklopfen",
      nl: "Het verleden kan aankloppen",
      es: "El pasado puede llamar",
      fr: "Le passé peut frapper à la porte",
      it: "Il passato potrebbe bussare",
    },
    meaning: {
      tr: "Eski bir tanıdık ya da aşktan haber alabilirsin. Bu karşılaşma seni düşündürecek.",
      en: "You might hear from an old acquaintance or love. This encounter will make you think.",
      zh: "你可能会收到旧相识或旧爱的消息。这次相遇会让你深思。",
      de: "Du könntest von einem alten Bekannten oder einer alten Liebe hören. Diese Begegnung wird dich zum Nachdenken bringen.",
      nl: "Je zou iets kunnen horen van een oude bekende of liefde. Deze ontmoeting zal je aan het denken zetten.",
      es: "Podrías saber de un viejo conocido o amor. Este encuentro te hará pensar.",
      fr: "Vous pourriez avoir des nouvelles d'une vieille connaissance ou d'un ancien amour. Cette rencontre vous fera réfléchir.",
      it: "Potresti avere notizie di una vecchia conoscenza o di un amore. Questo incontro ti farà riflettere.",
    },
    category: "Tam Ayna",
  },
  {
    time: "06:06",
    title: {
      tr: "Duygusal bağ güçleniyor",
      en: "Emotional bond strengthening",
      zh: "情感纽带正在加强",
      de: "Emotionale Bindung stärkt sich",
      nl: "Emotionele band versterkt",
      es: "El vínculo emocional se fortalece",
      fr: "Le lien émotionnel se renforce",
      it: "Il legame emotivo si rafforza",
    },
    meaning: {
      tr: "Aile içindeki ya da romantik bir ilişkide duygusal derinlik artıyor. Kalbinle konuşmanın tam zamanı.",
      en: "Emotional depth is increasing in a family or romantic relationship. It's time to listen to your heart.",
      zh: "家庭内部或浪漫关系中的情感深度正在增加。是时候倾听你的心声了。",
      de: "Die emotionale Tiefe in einer familiären oder romantischen Beziehung nimmt zu. Es ist Zeit, auf dein Herz zu hören.",
      nl: "De emotionele diepgang neemt toe in een familie- of romantische relatie. Het is tijd om naar je hart te luisteren.",
      es: "La profundidad emocional está aumentando en una relación familiar o romántica. Es hora de escuchar a tu corazón.",
      fr: "La profondeur émotionnelle augmente dans une relation familiale ou amoureuse. Il est temps d'écouter votre cœur.",
      it: "La profondità emotiva sta aumentando in una relazione familiare o romantica. È tempo di ascoltare il tuo cuore.",
    },
    category: "Tam Ayna",
  },
  {
    time: "07:07",
    title: {
      tr: "Şans kapıda",
      en: "Luck is at your door",
      zh: "好运临门",
      de: "Glück steht vor der Tür",
      nl: "Geluk staat voor de deur",
      es: "La suerte está a tu puerta",
      fr: "La chance est à votre porte",
      it: "La fortuna è alla tua porta",
    },
    meaning: {
      tr: "Evren sana şansını denemen için bir kapı açıyor. Yeni bir iş, teklif ya da tanışma mümkün.",
      en: "The universe is opening a door for you to try your luck. A new job, offer, or meeting is possible.",
      zh: "宇宙正在为你打开一扇尝试运气的门。可能会有新工作、新提议或新相遇。",
      de: "Das Universum öffnet dir eine Tür, um dein Glück zu versuchen. Ein neuer Job, ein Angebot oder ein Treffen ist möglich.",
      nl: "Het universum opent een deur voor je om je geluk te beproeven. Een nieuwe baan, aanbod of ontmoeting is mogelijk.",
      es: "El universo te está abriendo una puerta para que pruebes tu suerte. Un nuevo trabajo, oferta o reunión es posible.",
      fr: "L'univers vous ouvre une porte pour tenter votre chance. Un nouveau travail, une offre ou une rencontre est possible.",
      it: "L'universo ti sta aprendo una porta per tentare la fortuna. È possibile un nuovo lavoro, un'offerta o un incontro.",
    },
    category: "Tam Ayna",
  },
  {
    time: "08:08",
    title: {
      tr: "Bolluk enerjisi",
      en: "Abundance energy",
      zh: "丰盛的能量",
      de: "Fülle-Energie",
      nl: "Overvloedsenergie",
      es: "Energía de abundancia",
      fr: "Énergie d'abondance",
      it: "Energia di abbondanza",
    },
    meaning: {
      tr: "Maddi veya manevi bir kazanç kapıda. Evren, emeklerinin karşılığını vermeye hazırlanıyor.",
      en: "Material or spiritual gain is at your door. The universe is preparing to reward your efforts.",
      zh: "物质或精神上的收获就在你门口。宇宙正准备回报你的努力。",
      de: "Materieller oder spiritueller Gewinn steht vor der Tür. Das Universum bereitet sich darauf vor, deine Bemühungen zu belohnen.",
      nl: "Materiële of spirituele winst staat voor de deur. Het universum bereidt zich voor om je inspanningen te belonen.",
      es: "Una ganancia material o espiritual está a tu puerta. El universo se prepara para recompensar tus esfuerzos.",
      fr: "Un gain matériel ou spirituel est à votre porte. L'univers se prépare à récompenser vos efforts.",
      it: "Un guadagno materiale o spirituale è alla tua porta. L'universo si sta preparando a ricompensare i tuoi sforzi.",
    },
    category: "Tam Ayna",
  },
  {
    time: "09:09",
    title: {
      tr: "Kendine yönel",
      en: "Turn inward",
      zh: "转向内在",
      de: "Wende dich nach innen",
      nl: "Keer naar binnen",
      es: "Vuélvete hacia adentro",
      fr: "Tournez-vous vers l'intérieur",
      it: "Rivolgiti verso l'interno",
    },
    meaning: {
      tr: "Başkasını anlamadan önce kendini dinle. İçsel huzurun anahtarı şu anda sende saklı.",
      en: "Listen to yourself before understanding others. The key to inner peace is hidden within you right now.",
      zh: "在理解他人之前先倾听自己。内心平静的关键此刻就藏在你心中。",
      de: "Höre auf dich selbst, bevor du andere verstehst. Der Schlüssel zum inneren Frieden liegt gerade jetzt in dir verborgen.",
      nl: "Luister naar jezelf voordat je anderen begrijpt. De sleutel tot innerlijke vrede ligt nu in jou verborgen.",
      es: "Escúchate a ti mismo antes de entender a los demás. La clave de la paz interior está escondida dentro de ti ahora mismo.",
      fr: "Écoutez-vous avant de comprendre les autres. La clé de la paix intérieure est cachée en vous en ce moment.",
      it: "Ascolta te stesso prima di capire gli altri. La chiave della pace interiore è nascosta dentro di te in questo momento.",
    },
    category: "Tam Ayna",
  },
  {
    time: "10:10",
    title: {
      tr: "Yeni bir tanışma",
      en: "A new encounter",
      zh: "新的相遇",
      de: "Eine neue Begegnung",
      nl: "Een nieuwe ontmoeting",
      es: "Un nuevo encuentro",
      fr: "Une nouvelle rencontre",
      it: "Un nuovo incontro",
    },
    meaning: {
      tr: "Yakın zamanda hayatına yeni biri girebilir. Bu karşılaşma duygusal anlamda iz bırakacak.",
      en: "Someone new might enter your life soon. This encounter will leave an emotional mark.",
      zh: "一个新人可能很快会进入你的生活。这次相遇将在情感上留下印记。",
      de: "Jemand Neues könnte bald in dein Leben treten. Diese Begegnung wird emotionale Spuren hinterlassen.",
      nl: "Er kan binnenkort iemand nieuw in je leven komen. Deze ontmoeting zal een emotionele indruk achterlaten.",
      es: "Alguien nuevo podría entrar en tu vida pronto. Este encuentro dejará una marca emocional.",
      fr: "Quelqu'un de nouveau pourrait bientôt entrer dans votre vie. Cette rencontre laissera une marque émotionnelle.",
      it: "Qualcuno di nuovo potrebbe entrare presto nella tua vita. Questo incontro lascerà un segno emotivo.",
    },
    category: "Tam Ayna",
  },
  {
    time: "11:11",
    title: {
      tr: "Dilek zamanı",
      en: "Make a wish",
      zh: "许愿时刻",
      de: "Wünsch dir was",
      nl: "Doe een wens",
      es: "Pide un deseo",
      fr: "Fais un vœu",
      it: "Esprimi un desiderio",
    },
    meaning: {
      tr: "Evren dileklerini dinliyor. İçinden geçen neyse, şimdi onu netleştirme vakti.",
      en: "The universe is listening to your wishes. Whatever you're thinking, now is the time to clarify it.",
      zh: "宇宙正在倾听你的愿望。无论你在想什么，现在是明确它的时候。",
      de: "Das Universum hört deine Wünsche. Was auch immer du denkst, jetzt ist es Zeit, es zu klären.",
      nl: "Het universum luistert naar je wensen. Wat je ook denkt, nu is het tijd om het duidelijk te maken.",
      es: "El universo escucha tus deseos. Lo que sea que estés pensando, ahora es el momento de aclararlo.",
      fr: "L'univers écoute vos vœux. Quoi que vous pensiez, c'est le moment de le clarifier.",
      it: "L'universo ascolta i tuoi desideri. Qualunque cosa tu stia pensando, ora è il momento di chiarirla.",
    },
    category: "Tam Ayna",
  },
  {
    time: "12:12",
    title: {
      tr: "Ciddi düşünüyor",
      en: "Serious thoughts",
      zh: "严肃的想法",
      de: "Ernste Gedanken",
      nl: "Serieuze gedachten",
      es: "Pensamientos serios",
      fr: "Pensées sérieuses",
      it: "Pensieri seri",
    },
    meaning: {
      tr: "İlişkinizin özellikle ortalarındaysanız bu saate denk geldiğinizde bilin ki sizinle ilgili artık daha ciddi kararlar almak ve adımlar atmak istiyor. Bu yüzden sizin de bu konuda hazırlıklı olmanızda fayda var.",
      en: "If you're in the middle of your relationship, know that they want to take more serious decisions and steps about you. It's beneficial for you to be prepared for this.",
      zh: "如果你正处于关系的中间阶段，要知道他们想要对你做出更严肃的决定并采取行动。为此做好准备对你有好处。",
      de: "Wenn du mitten in einer Beziehung bist, wisse, dass sie ernstere Entscheidungen und Schritte in Bezug auf dich treffen wollen. Es ist gut für dich, darauf vorbereitet zu sein.",
      nl: "Als je midden in je relatie zit, weet dan dat ze serieuzere beslissingen en stappen over jou willen nemen. Het is goed voor je om hierop voorbereid te zijn.",
      es: "Si estás en medio de una relación, sabe que quieren tomar decisiones y pasos más serios sobre ti. Es beneficioso que estés preparado para esto.",
      fr: "Si vous êtes au milieu de votre relation, sachez qu'ils veulent prendre des décisions et des mesures plus sérieuses à votre sujet. Il est bénéfique pour vous d'y être préparé.",
      it: "Se sei nel mezzo della tua relazione, sappi che vogliono prendere decisioni e passi più seri su di te. È utile per te essere preparato a questo.",
    },
    category: "Tam Ayna",
  },
  {
    time: "13:13",
    title: {
      tr: "Güç sende",
      en: "Power is within you",
      zh: "力量在你心中",
      de: "Die Kraft liegt in dir",
      nl: "De kracht zit in jou",
      es: "El poder está en ti",
      fr: "Le pouvoir est en vous",
      it: "Il potere è dentro di te",
    },
    meaning: {
      tr: "Kendine güvenin arttığı bir dönemdesin. Cesur kararlar alabilir, hayatına yön verebilirsin.",
      en: "You're in a period of increased self-confidence. You can make brave decisions and direct your life.",
      zh: "你正处于自信心增强的时期。你可以做出勇敢的决定并掌控你的人生。",
      de: "Du befindest dich in einer Phase gesteigerten Selbstvertrauens. Du kannst mutige Entscheidungen treffen und dein Leben lenken.",
      nl: "Je bevindt je in een periode van toegenomen zelfvertrouwen. Je kunt moedige beslissingen nemen en je leven sturen.",
      es: "Estás en un período de mayor autoconfianza. Puedes tomar decisiones valientes y dirigir tu vida.",
      fr: "Vous êtes dans une période de confiance en soi accrue. Vous pouvez prendre des décisions courageuses et diriger votre vie.",
      it: "Sei in un periodo di maggiore fiducia in te stesso. Puoi prendere decisioni coraggiose e dirigere la tua vita.",
    },
    category: "Tam Ayna",
  },
  {
    time: "14:14",
    title: {
      tr: "Aklından çıkmıyorsun",
      en: "Can't get you off their mind",
      zh: "你在他们脑海中挥之不去",
      de: "Du gehst ihnen nicht aus dem Kopf",
      nl: "Ze kunnen je niet uit hun hoofd zetten",
      es: "No pueden sacarte de su mente",
      fr: "Ils ne peuvent pas vous sortir de leur tête",
      it: "Non riescono a toglierti dalla testa",
    },
    meaning: {
      tr: "Sürekli seni düşünüyor olabilir. Özellikle gün içinde sıkça seni hatırlıyor ve belki de aramak ya da yazmak için cesaret toplamaya çalışıyor.",
      en: "They might be thinking about you constantly. They remember you often during the day and might be gathering courage to call or write to you.",
      zh: "他们可能一直在想你。他们在白天经常想起你，可能正在鼓起勇气给你打电话或写信。",
      de: "Sie könnten ständig an dich denken. Sie erinnern sich tagsüber oft an dich und sammeln vielleicht Mut, um dich anzurufen oder dir zu schreiben.",
      nl: "Ze denken misschien constant aan je. Ze herinneren je vaak gedurende de dag en verzamelen misschien moed om je te bellen of te schrijven.",
      es: "Podrían estar pensando en ti constantemente. Te recuerdan a menudo durante el día y podrían estar reuniendo valor para llamarte o escribirte.",
      fr: "Ils pensent peut-être constamment à vous. Ils se souviennent souvent de vous pendant la journée et essaient peut-être de trouver le courage de vous appeler ou de vous écrire.",
      it: "Potrebbero pensare costantemente a te. Ti ricordano spesso durante il giorno e potrebbero cercare di raccogliere il coraggio per chiamarti o scriverti.",
    },
    category: "Tam Ayna",
  },
  {
    time: "15:15",
    title: {
      tr: "Yüreğinde bir kıpırtı var",
      en: "A flutter in their heart",
      zh: "他们心中悸动",
      de: "Ein Flattern in ihrem Herzen",
      nl: "Een fladdering in hun hart",
      es: "Un aleteo en su corazón",
      fr: "Un battement dans leur cœur",
      it: "Un battito nel loro cuore",
    },
    meaning: {
      tr: "Kalbini çarpıtan biri olabilir. Bu duygular karşılıklı olabilir, işaretleri takip et.",
      en: "Someone might be making your heart flutter. These feelings might be mutual, follow the signs.",
      zh: "可能有人让你心跳加速。这些感觉可能是相互的，跟随迹象。",
      de: "Jemand könnte dein Herz höher schlagen lassen. Diese Gefühle könnten gegenseitig sein, folge den Zeichen.",
      nl: "Iemand kan je hart sneller doen kloppen. Deze gevoelens kunnen wederzijds zijn, volg de tekens.",
      es: "Alguien podría estar haciendo que tu corazón se acelere. Estos sentimientos podrían ser mutuos, sigue las señales.",
      fr: "Quelqu'un pourrait faire battre votre cœur. Ces sentiments pourraient être réciproques, suivez les signes.",
      it: "Qualcuno potrebbe far battere il tuo cuore. Questi sentimenti potrebbero essere reciproci, segui i segni.",
    },
    category: "Tam Ayna",
  },
  {
    time: "16:16",
    title: {
      tr: "Zorluklar bitiyor",
      en: "Hardships are ending",
      zh: "苦难即将结束",
      de: "Schwierigkeiten enden",
      nl: "Moeilijkheden eindigen",
      es: "Las dificultades terminan",
      fr: "Les difficultés prennent fin",
      it: "Le difficoltà stanno finendo",
    },
    meaning: {
      tr: "Yaşadığın sıkıntılı süreç sona eriyor. Artık önün açık, ferah bir döneme giriyorsun.",
      en: "The troubled period you've been going through is ending. Your path is clear now, you're entering a spacious period.",
      zh: "你所经历的困难时期即将结束。现在的道路是清晰的，你正在进入一个宽广的时期。",
      de: "Die schwierige Zeit, die du durchgemacht hast, geht zu Ende. Dein Weg ist jetzt frei, du trittst in eine Phase der Erleichterung ein.",
      nl: "De moeilijke periode die je hebt doorgemaakt, loopt ten einde. Je pad is nu vrij, je gaat een periode van verlichting in.",
      es: "El período problemático por el que has pasado está terminando. Tu camino está despejado ahora, estás entrando en un período espacioso.",
      fr: "La période difficile que vous traversez touche à sa fin. Votre chemin est clair maintenant, vous entrez dans une période spacieuse.",
      it: "Il periodo difficile che hai attraversato sta finendo. Il tuo percorso è chiaro ora, stai entrando in un periodo spazioso.",
    },
    category: "Tam Ayna",
  },
  {
    time: "17:17",
    title: {
      tr: "Yaratıcılık artıyor",
      en: "Creativity rising",
      zh: "创造力提升",
      de: "Kreativität steigt",
      nl: "Creativiteit stijgt",
      es: "La creatividad aumenta",
      fr: "La créativité augmente",
      it: "La creatività aumenta",
    },
    meaning: {
      tr: "İlham perileri yanında. Sanatsal veya yaratıcı bir proje için harika bir dönemdesin.",
      en: "Muses are by your side. You are in a great period for an artistic or creative project.",
      zh: "缪斯女神在你身边。你正处于艺术或创意项目的绝佳时期。",
      de: "Musen sind an deiner Seite. Du befindest dich in einer großartigen Phase für ein künstlerisches oder kreatives Projekt.",
      nl: "Muzen staan aan je zijde. Je bevindt je in een geweldige periode voor een artistiek of creatief project.",
      es: "Las musas están a tu lado. Estás en un gran período para un proyecto artístico o creativo.",
      fr: "Les muses sont à vos côtés. Vous êtes dans une excellente période pour un projet artistique ou créatif.",
      it: "Le muse sono al tuo fianco. Sei in un ottimo periodo per un progetto artistico o creativo.",
    },
    category: "Tam Ayna",
  },
  {
    time: "18:18",
    title: {
      tr: "Bolluk akıyor",
      en: "Abundance flowing",
      zh: "丰盛在流动",
      de: "Fülle fließt",
      nl: "Overvloed stroomt",
      es: "La abundancia fluye",
      fr: "L'abondance coule",
      it: "L'abbondanza scorre",
    },
    meaning: {
      tr: "Maddi konularda şansın dönüyor. Beklediğin para ya da fırsat sana doğru geliyor.",
      en: "Your luck in financial matters is turning. The money or opportunity you've been waiting for is coming to you.",
      zh: "你在财务方面的运气正在好转。你等待的钱或机会正向你走来。",
      de: "Dein Glück in finanziellen Angelegenheiten wendet sich. Das Geld oder die Gelegenheit, auf die du gewartet hast, kommt auf dich zu.",
      nl: "Je geluk in financiële zaken keert. Het geld of de kans waar je op hebt gewacht, komt naar je toe.",
      es: "Tu suerte en asuntos financieros está cambiando. El dinero o la oportunidad que has estado esperando viene hacia ti.",
      fr: "Votre chance dans les affaires financières tourne. L'argent ou l'opportunité que vous attendiez vient à vous.",
      it: "La tua fortuna nelle questioni finanziarie sta cambiando. Il denaro o l'opportunità che stavi aspettando sta arrivando da te.",
    },
    category: "Tam Ayna",
  },
  {
    time: "19:19",
    title: {
      tr: "Sabırlı ol",
      en: "Be patient",
      zh: "保持耐心",
      de: "Sei geduldig",
      nl: "Wees geduldig",
      es: "Ten paciencia",
      fr: "Soyez patient",
      it: "Sii paziente",
    },
    meaning: {
      tr: "İstediğin şey için biraz daha zamana ihtiyaç var. Acele etme, her şey doğru zamanda olacak.",
      en: "A little more time is needed for what you want. Don't rush, everything will happen at the right time.",
      zh: "你想要的东西还需要一点时间。不要着急，一切都会在正确的时间发生。",
      de: "Für das, was du willst, wird noch etwas Zeit benötigt. Hetze nicht, alles wird zur richtigen Zeit geschehen.",
      nl: "Er is nog wat tijd nodig voor wat je wilt. Haast je niet, alles gebeurt op het juiste moment.",
      es: "Se necesita un poco más de tiempo para lo que quieres. No te apresures, todo sucederá en el momento adecuado.",
      fr: "Un peu plus de temps est nécessaire pour ce que vous voulez. Ne vous précipitez pas, tout arrivera au bon moment.",
      it: "C'è bisogno di un po' più di tempo per ciò che vuoi. Non avere fretta, tutto accadrà al momento giusto.",
    },
    category: "Tam Ayna",
  },
  {
    time: "20:20",
    title: {
      tr: "Acele etme",
      en: "Don't rush",
      zh: "不要匆忙",
      de: "Nicht hetzen",
      nl: "Niet haasten",
      es: "No te apresures",
      fr: "Ne vous précipitez pas",
      it: "Non avere fretta",
    },
    meaning: {
      tr: "Karar vermeden önce iyice düşün. Detayları gözden kaçırma, sakin kal.",
      en: "Think carefully before making a decision. Don't overlook details, stay calm.",
      zh: "做决定前要仔细思考。不要忽视细节，保持冷静。",
      de: "Denke sorgfältig nach, bevor du eine Entscheidung triffst. Übersehe keine Details, bleib ruhig.",
      nl: "Denk goed na voordat je een beslissing neemt. Zie geen details over het hoofd, blijf kalm.",
      es: "Piensa cuidadosamente antes de tomar una decisión. No pases por alto los detalles, mantén la calma.",
      fr: "Réfléchissez bien avant de prendre une décision. Ne négligez pas les détails, restez calme.",
      it: "Pensa attentamente prima di prendere una decisione. Non trascurare i dettagli, mantieni la calma.",
    },
    category: "Tam Ayna",
  },
  {
    time: "21:21",
    title: {
      tr: "Başarı seninle",
      en: "Success is with you",
      zh: "成功与你同在",
      de: "Erfolg ist mit dir",
      nl: "Succes is met jou",
      es: "El éxito está contigo",
      fr: "Le succès est avec vous",
      it: "Il successo è con te",
    },
    meaning: {
      tr: "Büyük bir başarıya imza atmak üzeresin. Kendine güven ve yolunda ilerle.",
      en: "You are about to achieve great success. Believe in yourself and move forward on your path.",
      zh: "你即将取得巨大的成功。相信自己，在你的道路上前行。",
      de: "Du stehst kurz davor, großen Erfolg zu erzielen. Glaube an dich selbst und geh deinen Weg weiter.",
      nl: "Je staat op het punt groot succes te behalen. Geloof in jezelf en ga verder op je pad.",
      es: "Estás a punto de lograr un gran éxito. Cree en ti mismo y avanza en tu camino.",
      fr: "Vous êtes sur le point de remporter un grand succès. Croyez en vous et avancez sur votre chemin.",
      it: "Stai per ottenere un grande successo. Credi in te stesso e vai avanti per la tua strada.",
    },
    category: "Tam Ayna",
  },
  {
    time: "22:22",
    title: {
      tr: "Ruh eşi enerjisi",
      en: "Soulmate energy",
      zh: "灵魂伴侣能量",
      de: "Seelenverwandten-Energie",
      nl: "Zielsverwant energie",
      es: "Energía de alma gemela",
      fr: "Énergie de l'âme sœur",
      it: "Energia dell'anima gemella",
    },
    meaning: {
      tr: "Hayatına giren biri ruh eşin olabilir. Bu bağı hafife alma, evren seni yönlendiriyor.",
      en: "Someone entering your life might be your soulmate. Don't take this connection lightly, the universe is guiding you.",
      zh: "进入你生活的人可能是你的灵魂伴侣。不要轻视这种联系，宇宙正在指引你。",
      de: "Jemand, der in dein Leben tritt, könnte dein Seelenverwandter sein. Nimm diese Verbindung nicht auf die leichte Schulter, das Universum führt dich.",
      nl: "Iemand die in je leven komt, kan je zielsverwant zijn. Neem deze verbinding niet licht op, het universum leidt je.",
      es: "Alguien que entra en tu vida podría ser tu alma gemela. No tomes esta conexión a la ligera, el universo te está guiando.",
      fr: "Quelqu'un qui entre dans votre vie pourrait être votre âme sœur. Ne prenez pas cette connexion à la légère, l'univers vous guide.",
      it: "Qualcuno che entra nella tua vita potrebbe essere la tua anima gemella. Non prendere questa connessione alla leggera, l'universo ti sta guidando.",
    },
    category: "Tam Ayna",
  },
  {
    time: "23:23",
    title: {
      tr: "İletişim önemli",
      en: "Communication is key",
      zh: "沟通是关键",
      de: "Kommunikation ist der Schlüssel",
      nl: "Communicatie is de sleutel",
      es: "La comunicación es clave",
      fr: "La communication est la clé",
      it: "La comunicazione è fondamentale",
    },
    meaning: {
      tr: "Partnerinle ya da yakınlarınla konuşman gereken konular var. İletişim kanallarını açık tut.",
      en: "There are issues you need to discuss with your partner or loved ones. Keep communication channels open.",
      zh: "有些问题你需要与伴侣或亲人讨论。保持沟通渠道畅通。",
      de: "Es gibt Themen, die du mit deinem Partner oder deinen Lieben besprechen musst. Halte die Kommunikationskanäle offen.",
      nl: "Er zijn kwesties die je met je partner of dierbaren moet bespreken. Houd de communicatiekanalen open.",
      es: "Hay temas que necesitas discutir con tu pareja o seres queridos. Mantén abiertos los canales de comunicación.",
      fr: "Il y a des problèmes que vous devez discuter avec votre partenaire ou vos proches. Gardez les canaux de communication ouverts.",
      it: "Ci sono questioni che devi discutere con il tuo partner o i tuoi cari. Mantieni aperti i canali di comunicazione.",
    },
    category: "Tam Ayna",
  },
  // Ters Aynalar (Reverse Mirrors)
  {
    time: "01:10",
    title: {
      tr: "Geçmiş seni özlüyor",
      en: "The past misses you",
      zh: "过去在想念你",
      de: "Die Vergangenheit vermisst dich",
      nl: "Het verleden mist je",
      es: "El pasado te extraña",
      fr: "Le passé vous manque",
      it: "Il passato ti manca",
    },
    meaning: {
      tr: "Eski bir tanıdık ya da aşk seni hâlâ aklında tutuyor olabilir. Belki de bir kapanış ya da yeniden doğuş zamanı gelmiştir.",
      en: "An old acquaintance or love might still be keeping you in mind. Perhaps it's time for closure or rebirth.",
      zh: "一位旧识或旧爱可能仍然把你放在心上。也许是时候结束或重生了。",
      de: "Ein alter Bekannter oder eine alte Liebe könnte dich noch im Kopf haben. Vielleicht ist es Zeit für einen Abschluss oder eine Wiedergeburt.",
      nl: "Een oude bekende of liefde kan je nog steeds in gedachten houden. Misschien is het tijd voor afsluiting of wedergeboorte.",
      es: "Un viejo conocido o amor podría tenerte todavía en mente. Quizás sea hora de un cierre o renacimiento.",
      fr: "Une vieille connaissance ou un ancien amour pourrait encore vous avoir à l'esprit. Il est peut-être temps de clore le chapitre ou de renaître.",
      it: "Una vecchia conoscenza o un amore potrebbe ancora averti in mente. Forse è tempo di chiusura o rinascita.",
    },
    category: "Ters Ayna",
  },
  {
    time: "02:20",
    title: {
      tr: "İyi haberler yolda",
      en: "Good news on the way",
      zh: "好消息在路上",
      de: "Gute Nachrichten sind unterwegs",
      nl: "Goed nieuws onderweg",
      es: "Buenas noticias en camino",
      fr: "De bonnes nouvelles en route",
      it: "Buone notizie in arrivo",
    },
    meaning: {
      tr: "Beklediğin o güzel haber çok yakında gelecek. Umudunu kaybetme.",
      en: "That good news you've been waiting for is coming very soon. Don't lose hope.",
      zh: "你等待的好消息很快就会到来。不要失去希望。",
      de: "Die guten Nachrichten, auf die du gewartet hast, kommen sehr bald. Verliere nicht die Hoffnung.",
      nl: "Dat goede nieuws waar je op hebt gewacht komt heel binnenkort. Verlies de hoop niet.",
      es: "Esas buenas noticias que has estado esperando llegarán muy pronto. No pierdas la esperanza.",
      fr: "Ces bonnes nouvelles que vous attendiez arrivent très bientôt. Ne perdez pas espoir.",
      it: "Quelle buone notizie che stavi aspettando stanno arrivando molto presto. Non perdere la speranza.",
    },
    category: "Ters Ayna",
  },
  {
    time: "03:30",
    title: {
      tr: "Arzuların belirginleşiyor",
      en: "Desires becoming clear",
      zh: "欲望变得清晰",
      de: "Wünsche werden klar",
      nl: "Verlangens worden duidelijk",
      es: "Los deseos se aclaran",
      fr: "Les désirs deviennent clairs",
      it: "I desideri diventano chiari",
    },
    meaning: {
      tr: "Ne istediğini artık daha net biliyorsun. Hedeflerine odaklan ve harekete geç.",
      en: "You now know more clearly what you want. Focus on your goals and take action.",
      zh: "你现在更清楚自己想要什么。专注于你的目标并采取行动。",
      de: "Du weißt jetzt klarer, was du willst. Konzentriere dich auf deine Ziele und handle.",
      nl: "Je weet nu duidelijker wat je wilt. Focus op je doelen en onderneem actie.",
      es: "Ahora sabes más claramente lo que quieres. Concéntrate en tus objetivos y toma medidas.",
      fr: "Vous savez maintenant plus clairement ce que vous voulez. Concentrez-vous sur vos objectifs et agissez.",
      it: "Ora sai più chiaramente cosa vuoi. Concentrati sui tuoi obiettivi e agisci.",
    },
    category: "Ters Ayna",
  },
  {
    time: "04:40",
    title: {
      tr: "Güç sende",
      en: "Power is yours",
      zh: "力量属于你",
      de: "Die Macht gehört dir",
      nl: "De kracht is van jou",
      es: "El poder es tuyo",
      fr: "Le pouvoir est à vous",
      it: "Il potere è tuo",
    },
    meaning: {
      tr: "Kendi gücünün farkına var. Zorlukların üstesinden gelebilecek kapasiteye sahipsin.",
      en: "Realize your own power. You have the capacity to overcome difficulties.",
      zh: "意识到你自己的力量。你有能力克服困难。",
      de: "Erkenne deine eigene Kraft. Du hast die Fähigkeit, Schwierigkeiten zu überwinden.",
      nl: "Realiseer je eigen kracht. Je hebt het vermogen om moeilijkheden te overwinnen.",
      es: "Date cuenta de tu propio poder. Tienes la capacidad de superar las dificultades.",
      fr: "Réalisez votre propre pouvoir. Vous avez la capacité de surmonter les difficultés.",
      it: "Renditi conto del tuo potere. Hai la capacità di superare le difficoltà.",
    },
    category: "Ters Ayna",
  },
  {
    time: "05:50",
    title: {
      tr: "Sürpriz gelişme",
      en: "Surprise development",
      zh: "意外的发展",
      de: "Überraschende Entwicklung",
      nl: "Verrassende ontwikkeling",
      es: "Desarrollo sorpresa",
      fr: "Développement surprise",
      it: "Sviluppo a sorpresa",
    },
    meaning: {
      tr: "Hiç beklemediğin bir anda güzel bir sürprizle karşılaşabilirsin. Hazırlıklı ol.",
      en: "You might encounter a nice surprise when you least expect it. Be prepared.",
      zh: "你可能会在你最意想不到的时候遇到惊喜。做好准备。",
      de: "Du könntest eine schöne Überraschung erleben, wenn du es am wenigsten erwartest. Sei vorbereitet.",
      nl: "Je kunt een leuke verrassing tegenkomen wanneer je het het minst verwacht. Wees voorbereid.",
      es: "Podrías encontrar una agradable sorpresa cuando menos lo esperes. Prepárate.",
      fr: "Vous pourriez rencontrer une belle surprise au moment où vous vous y attendez le moins. Soyez prêt.",
      it: "Potresti incontrare una bella sorpresa quando meno te lo aspetti. Sii preparato.",
    },
    category: "Ters Ayna",
  },
  {
    time: "10:01",
    title: {
      tr: "Haber seni bulacak",
      en: "News will find you",
      zh: "消息会找到你",
      de: "Nachrichten werden dich finden",
      nl: "Nieuws zal je vinden",
      es: "Las noticias te encontrarán",
      fr: "Les nouvelles vous trouveront",
      it: "Le notizie ti troveranno",
    },
    meaning: {
      tr: "Kulağına bir dedikodu ya da ilginç bir haber gelebilir. Duyduklarını sorgulamadan önce doğruluğunu tart.",
      en: "You might hear a rumor or interesting news. Weigh its truth before questioning what you hear.",
      zh: "你可能会听到谣言或有趣的消息。在质疑你听到的内容之前，先权衡其真实性。",
      de: "Du könntest ein Gerücht oder interessante Neuigkeiten hören. Wäge die Wahrheit ab, bevor du das Gehörte in Frage stellst.",
      nl: "Je kunt een gerucht of interessant nieuws horen. Weeg de waarheid af voordat je twijfelt aan wat je hoort.",
      es: "Podrías escuchar un rumor o noticias interesantes. Sopesa su veracidad antes de cuestionar lo que escuchas.",
      fr: "Vous pourriez entendre une rumeur ou des nouvelles intéressantes. Pesez sa vérité avant de remettre en question ce que vous entendez.",
      it: "Potresti sentire una voce o notizie interessanti. Valuta la sua verità prima di mettere in discussione ciò che senti.",
    },
    category: "Ters Ayna",
  },
  {
    time: "12:21",
    title: {
      tr: "Kalbine yakın",
      en: "Close to their heart",
      zh: "靠近他们的心",
      de: "Nah an ihrem Herzen",
      nl: "Dicht bij hun hart",
      es: "Cerca de su corazón",
      fr: "Proche de leur cœur",
      it: "Vicino al loro cuore",
    },
    meaning: {
      tr: "Birinin seni düşündüğü ve sana duygusal olarak yaklaştığı bir an. Bu bağ giderek güçleniyor olabilir.",
      en: "A moment when someone is thinking of you and emotionally approaching you. This connection might be growing stronger.",
      zh: "有人在想念你并在情感上接近你的时刻。这种联系可能正在变得越来越强。",
      de: "Ein Moment, in dem jemand an dich denkt und sich dir emotional nähert. Diese Verbindung könnte stärker werden.",
      nl: "Een moment waarop iemand aan je denkt en je emotioneel benadert. Deze band kan sterker worden.",
      es: "Un momento en el que alguien está pensando en ti y acercándose emocionalmente. Esta conexión podría estar fortaleciéndose.",
      fr: "Un moment où quelqu'un pense à vous et se rapproche émotionnellement de vous. Cette connexion pourrait se renforcer.",
      it: "Un momento in cui qualcuno ti sta pensando e si sta avvicinando emotivamente a te. Questa connessione potrebbe rafforzarsi.",
    },
    category: "Ters Ayna",
  },
  {
    time: "13:31",
    title: {
      tr: "Olumsuz düşünceler",
      en: "Negative thoughts",
      zh: "消极的想法",
      de: "Negative Gedanken",
      nl: "Negatieve gedachten",
      es: "Pensamientos negativos",
      fr: "Pensées négatives",
      it: "Pensieri negativi",
    },
    meaning: {
      tr: "Zihnini kurcalayan kötü düşüncelerden arınmalısın. Olaylara daha pozitif bakmayı dene.",
      en: "You should cleanse yourself of bad thoughts troubling your mind. Try to look at things more positively.",
      zh: "你应该清除困扰你头脑的坏想法。试着更积极地看待事情。",
      de: "Du solltest dich von schlechten Gedanken reinigen, die deinen Geist plagen. Versuche, die Dinge positiver zu sehen.",
      nl: "Je moet jezelf reinigen van slechte gedachten die je geest kwellen. Probeer de dingen positiever te bekijken.",
      es: "Deberías limpiarte de los malos pensamientos que turban tu mente. Intenta ver las cosas de manera más positiva.",
      fr: "Vous devriez vous purifier des mauvaises pensées qui troublent votre esprit. Essayez de voir les choses de manière plus positive.",
      it: "Dovresti purificarti dai cattivi pensieri che turbano la tua mente. Cerca di guardare le cose in modo più positivo.",
    },
    category: "Ters Ayna",
  },
  {
    time: "14:41",
    title: {
      tr: "Şans seninle",
      en: "Luck is with you",
      zh: "好运与你同在",
      de: "Das Glück ist mit dir",
      nl: "Geluk is met jou",
      es: "La suerte está contigo",
      fr: "La chance est avec vous",
      it: "La fortuna è con te",
    },
    meaning: {
      tr: "Beklenmedik bir yerden güzel bir haber gelebilir. Şans kapını çalmak üzere.",
      en: "Good news might come from an unexpected place. Luck is about to knock on your door.",
      zh: "好消息可能会从意想不到的地方传来。好运即将敲响你的门。",
      de: "Gute Nachrichten könnten von einem unerwarteten Ort kommen. Das Glück klopft gleich an deine Tür.",
      nl: "Goed nieuws kan uit onverwachte hoek komen. Geluk staat op het punt aan je deur te kloppen.",
      es: "Buenas noticias podrían llegar de un lugar inesperado. La suerte está a punto de llamar a tu puerta.",
      fr: "De bonnes nouvelles pourraient venir d'un endroit inattendu. La chance est sur le point de frapper à votre porte.",
      it: "Buone notizie potrebbero arrivare da un luogo inaspettato. La fortuna sta per bussare alla tua porta.",
    },
    category: "Ters Ayna",
  },
  {
    time: "15:51",
    title: {
      tr: "Eski bir aşk",
      en: "An old love",
      zh: "一段旧爱",
      de: "Eine alte Liebe",
      nl: "Een oude liefde",
      es: "Un viejo amor",
      fr: "Un vieil amour",
      it: "Un vecchio amore",
    },
    meaning: {
      tr: "Geçmişten gelen biri tekrar hayatına girmek isteyebilir. Karar senin, ama dikkatli ol.",
      en: "Someone from the past might want to re-enter your life. The decision is yours, but be careful.",
      zh: "来自过去的人可能想重新进入你的生活。决定权在你，但要小心。",
      de: "Jemand aus der Vergangenheit möchte vielleicht wieder in dein Leben treten. Die Entscheidung liegt bei dir, aber sei vorsichtig.",
      nl: "Iemand uit het verleden wil misschien weer in je leven komen. De beslissing is aan jou, maar wees voorzichtig.",
      es: "Alguien del pasado podría querer volver a entrar en tu vida. La decisión es tuya, pero ten cuidado.",
      fr: "Quelqu'un du passé pourrait vouloir réintégrer votre vie. La décision vous appartient, mais soyez prudent.",
      it: "Qualcuno del passato potrebbe voler rientrare nella tua vita. La decisione è tua, ma fai attenzione.",
    },
    category: "Ters Ayna",
  },
  {
    time: "20:02",
    title: {
      tr: "Aranızda mesafe var",
      en: "There's distance between you",
      zh: "你们之间有距离",
      de: "Es gibt Distanz zwischen euch",
      nl: "Er is afstand tussen jullie",
      es: "Hay distancia entre vosotros",
      fr: "Il y a de la distance entre vous",
      it: "C'è distanza tra di voi",
    },
    meaning: {
      tr: "Fiziksel ya da duygusal bir uzaklık ilişkine etki ediyor olabilir. Köprü kurmak için sen ilk adımı atabilirsin.",
      en: "A physical or emotional distance might be affecting your relationship. You can take the first step to build a bridge.",
      zh: "身体或情感上的距离可能会影响你们的关系。你可以迈出第一步来搭建桥梁。",
      de: "Eine physische oder emotionale Distanz könnte deine Beziehung beeinträchtigen. Du kannst den ersten Schritt machen, um eine Brücke zu bauen.",
      nl: "Een fysieke of emotionele afstand kan je relatie beïnvloeden. Jij kunt de eerste stap zetten om een brug te slaan.",
      es: "Una distancia física o emocional podría estar afectando tu relación. Puedes dar el primer paso para construir un puente.",
      fr: "Une distance physique ou émotionnelle pourrait affecter votre relation. Vous pouvez faire le premier pas pour construire un pont.",
      it: "Una distanza fisica o emotiva potrebbe influenzare la tua relazione. Puoi fare il primo passo per costruire un ponte.",
    },
    category: "Ters Ayna",
  },
  {
    time: "21:12",
    title: {
      tr: "Sana ihtiyacı var",
      en: "They need you",
      zh: "他们需要你",
      de: "Sie brauchen dich",
      nl: "Ze hebben je nodig",
      es: "Te necesitan",
      fr: "Ils ont besoin de vous",
      it: "Hanno bisogno di te",
    },
    meaning: {
      tr: "Sevdiğin birinin desteğine ihtiyacı olabilir. Etrafına dikkatlice bak, yardım elini uzat.",
      en: "Someone you love might need your support. Look around carefully, extend a helping hand.",
      zh: "你爱的人可能需要你的支持。仔细环顾四周，伸出援手。",
      de: "Jemand, den du liebst, könnte deine Unterstützung brauchen. Schau dich genau um, reiche eine helfende Hand.",
      nl: "Iemand van wie je houdt, heeft misschien je steun nodig. Kijk goed om je heen, reik een helpende hand.",
      es: "Alguien a quien amas podría necesitar tu apoyo. Mira a tu alrededor con cuidado, extiende una mano amiga.",
      fr: "Quelqu'un que vous aimez pourrait avoir besoin de votre soutien. Regardez attentivement autour de vous, tendez une main secourable.",
      it: "Qualcuno che ami potrebbe aver bisogno del tuo supporto. Guardati intorno attentamente, tendi una mano.",
    },
    category: "Ters Ayna",
  },
  {
    time: "23:32",
    title: {
      tr: "Dikkatli ol",
      en: "Be careful",
      zh: "小心",
      de: "Sei vorsichtig",
      nl: "Wees voorzichtig",
      es: "Ten cuidado",
      fr: "Soyez prudent",
      it: "Fai attenzione",
    },
    meaning: {
      tr: "Biri senin hakkında konuşuyor ya da arkandan iş çeviriyor olabilir. Kimseye hemen güvenme.",
      en: "Someone might be talking about you or plotting behind your back. Don't trust anyone immediately.",
      zh: "有人可能在谈论你或在背后搞鬼。不要立刻相信任何人。",
      de: "Jemand könnte über dich reden oder hinter deinem Rücken intrigieren. Vertraue niemandem sofort.",
      nl: "Iemand praat misschien over je of smeedt plannen achter je rug om. Vertrouw niemand onmiddellijk.",
      es: "Alguien podría estar hablando de ti o conspirando a tus espaldas. No confíes en nadie inmediatamente.",
      fr: "Quelqu'un pourrait parler de vous ou comploter dans votre dos. Ne faites confiance à personne immédiatement.",
      it: "Qualcuno potrebbe parlare di te o complottare alle tue spalle. Non fidarti di nessuno immediatamente.",
    },
    category: "Ters Ayna",
  },
  // Üçlü Aynalar (Triple Mirrors)
  {
    time: "01:11",
    title: {
      tr: "Düşüncelerin güç kazanıyor",
      en: "Your thoughts are gaining power",
      zh: "你的思想正在获得力量",
      de: "Deine Gedanken gewinnen an Kraft",
      nl: "Je gedachten winnen aan kracht",
      es: "Tus pensamientos están ganando poder",
      fr: "Vos pensées gagnent en puissance",
      it: "I tuoi pensieri stanno guadagnando potere",
    },
    meaning: {
      tr: "Ne düşünüyorsan o olmaya başlıyor. Zihnini negatiften arındır ve niyetlerine odaklan, evren seni duyuyor.",
      en: "What you think is starting to manifest. Clear your mind of negativity and focus on your intentions, the universe is listening.",
      zh: "你的想法正在开始显化。清除头脑中的消极情绪，专注于你的意图，宇宙正在倾听。",
      de: "Was du denkst, beginnt sich zu manifestieren. Reinige deinen Geist von Negativität und konzentriere dich auf deine Absichten, das Universum hört zu.",
      nl: "Wat je denkt, begint zich te manifesteren. Maak je geest vrij van negativiteit en focus op je intenties, het universum luistert.",
      es: "Lo que piensas está empezando a manifestarse. Limpia tu mente de negatividad y concéntrate en tus intenciones, el universo está escuchando.",
      fr: "Ce que vous pensez commence à se manifester. Videz votre esprit de la négativité et concentrez-vous sur vos intentions, l'univers écoute.",
      it: "Ciò che pensi sta iniziando a manifestarsi. Libera la mente dalla negatività e concentrati sulle tue intenzioni, l'universo sta ascoltando.",
    },
    category: "Üçlü Ayna",
  },
  {
    time: "02:22",
    title: {
      tr: "Denge arayışı",
      en: "Seeking balance",
      zh: "寻求平衡",
      de: "Suche nach Gleichgewicht",
      nl: "Op zoek naar balans",
      es: "Buscando equilibrio",
      fr: "Recherche d'équilibre",
      it: "Alla ricerca dell'equilibrio",
    },
    meaning: {
      tr: "İçinde ya da ilişkinde bir denge kurman gerekiyor. Her şeyin uyumla ilerlemesi için önce kendi iç huzurunu bulmalısın.",
      en: "You need to establish balance within yourself or in your relationship. To have everything progress harmoniously, you must first find your inner peace.",
      zh: "你需要在内心或关系中建立平衡。为了让一切和谐发展，你必须首先找到内心的平静。",
      de: "Du musst ein Gleichgewicht in dir selbst oder in deiner Beziehung herstellen. Damit alles harmonisch voranschreitet, musst du zuerst deinen inneren Frieden finden.",
      nl: "Je moet balans vinden in jezelf of in je relatie. Om alles harmonieus te laten verlopen, moet je eerst je innerlijke rust vinden.",
      es: "Necesitas establecer equilibrio dentro de ti mismo o en tu relación. Para que todo progrese armoniosamente, primero debes encontrar tu paz interior.",
      fr: "Vous devez établir un équilibre en vous-même ou dans votre relation. Pour que tout progresse harmonieusement, vous devez d'abord trouver votre paix intérieure.",
      it: "Devi stabilire un equilibrio dentro di te o nella tua relazione. Perché tutto proceda armoniosamente, devi prima trovare la tua pace interiore.",
    },
    category: "Üçlü Ayna",
  },
  {
    time: "03:33",
    title: {
      tr: "Yolun açık, destek seninle",
      en: "Your path is clear, support is with you",
      zh: "你的道路清晰，支持与你同在",
      de: "Dein Weg ist frei, Unterstützung ist bei dir",
      nl: "Je pad is vrij, steun is bij je",
      es: "Tu camino está despejado, el apoyo está contigo",
      fr: "Votre chemin est clair, le soutien est avec vous",
      it: "Il tuo percorso è chiaro, il supporto è con te",
    },
    meaning: {
      tr: "Manevi rehberler ve evren sana arkanızda olduğunu hissettirmeye çalışıyor. Kararsız kaldıysan iç sesini takip et.",
      en: "Spiritual guides and the universe are trying to show you they're behind you. If you're uncertain, follow your inner voice.",
      zh: "精神向导和宇宙正试图向你展示他们就在你身后。如果你犹豫不决，跟随你的内心声音。",
      de: "Spirituelle Führer und das Universum versuchen dir zu zeigen, dass sie hinter dir stehen. Wenn du unsicher bist, folge deiner inneren Stimme.",
      nl: "Spirituele gidsen en het universum proberen je te laten zien dat ze achter je staan. Als je onzeker bent, volg dan je innerlijke stem.",
      es: "Los guías espirituales y el universo intentan mostrarte que están detrás de ti. Si estás indeciso, sigue tu voz interior.",
      fr: "Les guides spirituels et l'univers essaient de vous montrer qu'ils sont derrière vous. Si vous êtes incertain, suivez votre voix intérieure.",
      it: "Le guide spirituali e l'universo stanno cercando di mostrarti che sono dietro di te. Se sei incerto, segui la tua voce interiore.",
    },
    category: "Üçlü Ayna",
  },
  {
    time: "04:44",
    title: {
      tr: "Köklü değişim geliyor",
      en: "Fundamental change is coming",
      zh: "根本性的变化即将来临",
      de: "Grundlegende Veränderung kommt",
      nl: "Fundamentele verandering komt eraan",
      es: "Viene un cambio fundamental",
      fr: "Un changement fondamental arrive",
      it: "È in arrivo un cambiamento fondamentale",
    },
    meaning: {
      tr: "Hayatında sağlam temeller kurmak üzeresin. Bu saat, sıkı çalışmanın ve sabrın ödüllendirileceğini müjdeliyor.",
      en: "You're about to build solid foundations in your life. This hour heralds that hard work and patience will be rewarded.",
      zh: "你即将在生活中建立坚实的基础。这个时刻预示着努力工作和耐心将得到回报。",
      de: "Du bist dabei, solide Fundamente in deinem Leben zu bauen. Diese Stunde kündigt an, dass harte Arbeit und Geduld belohnt werden.",
      nl: "Je staat op het punt solide fundamenten in je leven te bouwen. Dit uur kondigt aan dat hard werken en geduld beloond zullen worden.",
      es: "Estás a punto de construir cimientos sólidos en tu vida. Esta hora anuncia que el trabajo duro y la paciencia serán recompensados.",
      fr: "Vous êtes sur le point de bâtir des fondations solides dans votre vie. Cette heure annonce que le travail acharné et la patience seront récompensés.",
      it: "Stai per costruire solide fondamenta nella tua vita. Quest'ora annuncia che il duro lavoro e la pazienza saranno ricompensati.",
    },
    category: "Üçlü Ayna",
  },
  {
    time: "05:55",
    title: {
      tr: "Ani bir gelişmeye hazır ol",
      en: "Be ready for a sudden development",
      zh: "准备好迎接突发进展",
      de: "Sei bereit für eine plötzliche Entwicklung",
      nl: "Wees voorbereid op een plotselinge ontwikkeling",
      es: "Prepárate para un desarrollo repentino",
      fr: "Soyez prêt pour un développement soudain",
      it: "Sii pronto per uno sviluppo improvviso",
    },
    meaning: {
      tr: "Beklenmedik bir haber ya da değişim kapında. Bu yenilik önce seni sarsabilir ama sonunda hayrına olacak.",
      en: "An unexpected news or change is at your door. This novelty might shake you at first but will be for your benefit in the end.",
      zh: "意外的消息或变化就在门口。这种新奇可能会一开始让你震惊，但最终会对你有利。",
      de: "Unerwartete Nachrichten oder Veränderungen stehen vor der Tür. Diese Neuerung könnte dich zuerst erschüttern, wird aber am Ende zu deinem Besten sein.",
      nl: "Onverwacht nieuws of verandering staat voor de deur. Deze nieuwigheid kan je in het begin schokken, maar zal uiteindelijk in je voordeel zijn.",
      es: "Noticias o cambios inesperados están a tu puerta. Esta novedad podría sacudirte al principio, pero será para tu beneficio al final.",
      fr: "Des nouvelles ou des changements inattendus sont à votre porte. Cette nouveauté pourrait vous secouer au début mais sera pour votre bien à la fin.",
      it: "Notizie o cambiamenti inaspettati sono alla tua porta. Questa novità potrebbe scuoterti all'inizio ma sarà a tuo beneficio alla fine.",
    },
    category: "Üçlü Ayna",
  },
];

// Helper function to map category to translation key
export function getCategoryTranslationKey(category: string): string {
  switch (category) {
    case "Tam Ayna":
      return "fullMirror";
    case "Ters Ayna":
      return "reverseMirror";
    case "Üçlü Ayna":
      return "tripleMirror";
    default:
      return category;
  }
}

export function isMirrorHour(time: string): MirrorHour | null {
  return mirrorHoursData.find((hour) => hour.time === time) || null;
}

export function getMirrorHourMeaning(
  time: string,
  locale: string = "tr"
): string {
  const mirrorHour = mirrorHoursData.find((hour) => hour.time === time);
  return mirrorHour
    ? mirrorHour.meaning[locale as keyof LocalizedText] || mirrorHour.meaning.en
    : "";
}

export function getMirrorHourTitle(
  time: string,
  locale: string = "tr"
): string {
  const mirrorHour = mirrorHoursData.find((hour) => hour.time === time);
  return mirrorHour
    ? mirrorHour.title[locale as keyof LocalizedText] || mirrorHour.title.en
    : "";
}

export function getMirrorHourCategory(time: string): string {
  const mirrorHour = mirrorHoursData.find((hour) => hour.time === time);
  return mirrorHour ? mirrorHour.category : "";
}

export function getAllMirrorHours(): MirrorHour[] {
  return mirrorHoursData;
}
